-- Criação da tabela de tipos de moradia
CREATE TABLE IF NOT EXISTS public.housing_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Popula tipos iniciais de moradia
INSERT INTO public.housing_types (name) VALUES 
('Casa com pátio fechado'),
('Casa sem pátio fechado'),
('Apartamento com telas de proteção'),
('Apartamento sem telas de proteção'),
('Chácara / Sítio')
ON CONFLICT DO NOTHING;

-- Criação da tabela de preferências do adotante para o sistema de match
CREATE TABLE IF NOT EXISTS public.adopter_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profiles_id UUID NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
    housing_types_id BIGINT REFERENCES public.housing_types(id) ON DELETE SET NULL,
    has_children BOOLEAN DEFAULT false NOT NULL,
    children_age_min INT,
    has_other_dogs BOOLEAN DEFAULT false NOT NULL,
    has_other_cats BOOLEAN DEFAULT false NOT NULL,
    hours_alone_per_day INT DEFAULT 4 NOT NULL,
    first_time_owner BOOLEAN DEFAULT false NOT NULL,
    accepts_special_needs BOOLEAN DEFAULT false NOT NULL,
    search_radius_km INT DEFAULT 50,
    preferred_species TEXT DEFAULT 'all' NOT NULL, -- 'dog', 'cat', 'all'
    preferred_sizes TEXT[] DEFAULT ARRAY['small', 'medium', 'large'] NOT NULL,
    match_vector TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criação de índices para performance de busca e integridade
CREATE INDEX IF NOT EXISTS idx_adopter_preferences_profiles_id ON public.adopter_preferences(profiles_id);
CREATE INDEX IF NOT EXISTS idx_adopter_preferences_housing_types_id ON public.adopter_preferences(housing_types_id);

-- Habilitação de Row Level Security (RLS)
ALTER TABLE public.housing_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adopter_preferences ENABLE ROW LEVEL SECURITY;

-- Políticas para housing_types (Leitura pública para qualquer usuário autenticado)
CREATE POLICY "Leitura de tipos de moradia para usuários autenticados"
ON public.housing_types FOR SELECT
TO authenticated
USING (true);

-- Políticas para adopter_preferences (Cada usuário gerencia apenas suas próprias preferências)
CREATE POLICY "Usuários podem visualizar suas próprias preferências"
ON public.adopter_preferences FOR SELECT
TO authenticated
USING (auth.uid() = profiles_id);

CREATE POLICY "Usuários podem inserir suas próprias preferências"
ON public.adopter_preferences FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = profiles_id);

CREATE POLICY "Usuários podem atualizar suas próprias preferências"
ON public.adopter_preferences FOR UPDATE
TO authenticated
USING (auth.uid() = profiles_id)
WITH CHECK (auth.uid() = profiles_id);